### PR TITLE
Fix dts-gen tsc/lint

### PR DESCRIPTION
**Pull request by potaracom**
## Why
dts-genのnpm run build、npm run tscがエラーになる

## What
パッケージのインストール
ESLintエラーの対応

## How to test
`yarn lint` and `yarn test` on the root directory.

## Checklist

- [x] Read [CONTRIBUTING.md](https://github.com/kintone/js-sdk/blob/master/CONTRIBUTING.md)
- [x] Updated documentation if it is required.
- [x] Added tests if it is required.
- [x] Passed `yarn lint` and `yarn test` on the root directory.

### CODE REVIEW

**Comment by chick-p** [comment]
@potaracom 
Thank you for your PR!

Sorry, this repository is premised on Yarn.
Could you check to pass npm-scripts with Yarn by referring [CONTRIBUTING.md](https://github.com/kintone/js-sdk/blob/master/CONTRIBUTING.md#for-contributors), please?

**Comment by potaracom** [comment]
@chick-p 
Sorry, please tell me more.

Your build failed?
or Does that mean the build doesn't get an error?

I am looking https://kintone.github.io/dts-gen/docs/#/maintenance-guide
> How to build
> Just run npm run build.

I tried. But, I got error 'eslint: not found'.
```
$ cd js-sdk/packages/dts-gen
$ npm run build
```

Should I modify the maintenance-guide?

**Comment by koba04** [comment]
@potaracom Thank you for your investigation.
> I am looking https://kintone.github.io/dts-gen/docs/#/maintenance-guide

The documentation is outdated because we are using `yarn` as a package manager on `js-sdk`.
You can see the instruction on the link @chick-p's comment https://github.com/kintone/js-sdk/pull/457#issuecomment-706897318.

You can build `dts-gen` by the following way.

```
% cd js-sdk
% yarn install
% cd dts-gen
% yarn build
```

Before buidling `dts-gen`, you have to install `yarn`.
https://yarnpkg.com/getting-started/install.

I'll fixed the outdated documentation as https://github.com/kintone/js-sdk/pull/463. Thank you!

**Comment by koba04** [comment]
@potaracom 
We've fixed the issue in the documentation of `dts-gen` as https://github.com/kintone/js-sdk/pull/463, so I'll close this issue.
If you still have any problems, please let us know. Thank you for your work 👏

**Pull request closed without merging**
