### PR TITLE
fix(deps): update dependency webpack to v5

### PR DESCRIPTION
**Pull request by shisama**
## Why

Updating webpack to v5 needs some fix and updating webpack-cli to v4 as well.
This includes them in addition to the PR by renovate.

## What

- Update webpack to v5 by renovate bot. 
- Update webpack-cli to v4
- Remove @types/webpack that doesn't need any longer
- Add some Node.js polyfills because webpack 5 does no longer include a polyfill for Node.js core API. [Webpack 5 release (2020-10-10) | webpack](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed)
  - [node-libs-browser](https://github.com/webpack/node-libs-browser) indicates the polyfills webpack used previously.
- webpack doesn't provide Plugin type definition. However, it provides [WebpackPluginInstance](https://github.com/webpack/webpack/blob/83790375529c5b2967d45ed40700399e107d478f/declarations/WebpackOptions.d.ts#L1485) so that it is the replacement of [Plugin from @types/webpack](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5a6d8f9fb714afbad6d0d993638da7c6c24ae3fd/types/webpack/index.d.ts#L1446)

## How to test

```bash
> yarn lint
> yarn test
> yarn build
```

## Checklist

- [x] Read [CONTRIBUTING.md](https://github.com/kintone/js-sdk/blob/master/CONTRIBUTING.md)
- [ ] Updated documentation if it is required.
- [ ] Added tests if it is required.
- [x] Passed `yarn lint` and `yarn test` on the root directory.

### CODE REVIEW

**Comment by koba04** [comment]
@shisama Great work 👍 
`plugin-packer` seems not to work on the web.
https://pr-475.d1ite8zvzg8c5i.amplifyapp.com/

I've seen the following error when uploading a plugin zip. Could you take a look? 
image

**Comment by shisama** [comment]
@koba04 Thanks! I tried plugin-packer page but no errors occur. However, I made a mistake and fixed it. Would you try it again in https://pr-475.d1ite8zvzg8c5i.amplifyapp.com

**Comment by koba04** [comment]
@shisama Thank you! I've confirmed it has been fixed 👍

**Comment by chick-p** [comment]
@shisama 
Thank you for your works!!

If the plugin-packer page supports IE browser, it not working on IE.
The generated file includes arrow functions.



> By default, webpack's runtime code uses ES2015 syntax to build smaller bundles. If your build targets environments that don't support this syntax (like IE11), you'll need to set target: ['web', 'es5'] to revert to ES5 syntax ('web' if target environment is browser).
ref. https://webpack.js.org/migrate/5/#clean-up-configuration

**Comment by shisama** [comment]
@chick-p Thank you for reviewing and checking this in IE11. Good catch. I didn't realize it doesn't run in IE11.
However, the web page of plugin-packer supports only modern browsers. So, I think it seems not to be necessary to run it in IE11. Please take a look at https://github.com/kintone/js-sdk/tree/master/packages/plugin-packer.

**Review by koba04 — APPROVED** [review]
👍

**Review by chick-p — APPROVED** [review]
@shisama 
Sorry..., I overlooked "modern browsers" in README.
I agree that not to be necessary to run it in IE11!

**Comment by shisama** [comment]
@koba04 @chick-p Thank you for your review. Would you please merge this if you have no issues and questions?

**Comment by koba04** [comment]
LTGM 👍  Could you resolve the conflicts?

**Comment by shisama** [comment]
@koba04 Thanks! Resolved.

**Comment by koba04** [comment]
🚀 🚀 🚀

**Pull request merged**
