### PR TITLE
fix(plugin-uploader): System ENV value check

### PR DESCRIPTION
**Pull request by charleslee0212**
env variable should not be empty.

## Why

The isSet function check to see if the env value is a type string; however, in the cli flags for the env are all defined as type string defeating the purpose of the isSet function. This results in not prompting the user to fill out the necessary values to run the kintone plugin uploader. The code will throw an error. This is a bug.

## What

I have updated the code to also check the value of the env. If the value is an empty string, isSet will return false.

## How to test

Run the kintone plugin uploader without initializing env variables. Then see if the code will prompt the user.

## Checklist

- [x] Read [CONTRIBUTING.md](https://github.com/kintone/js-sdk/blob/main/CONTRIBUTING.md)
- [x] Updated documentation if it is required.
- [x] Added tests if it is required.
- [x] Passed `pnpm lint` and `pnpm test` on the root directory.

### CODE REVIEW

**Comment by chihiro-adachi** [comment]
@charleslee0212 
Thank you!
Please check the following two points.

- It looks like the CI is down, so could you check that?
- Is it possible to create a unit test for this fix?

**Comment by chihiro-adachi** [comment]
プロンプトが動作することを確認。

```
$ unset KINTONE_BASE_URL
$ unset KINTONE_USERNAME
$ unset KINTONE_PASSWORD
$ bin/cli.js /path/to/plugin.zip
? kintoneのベースURLを入力してください (https://example.cybozu.com): http://localhost
? ログイン名を入力してください: username
? パスワードを入力してください: password
Open http://localhost/login?saml=off
Trying to log in...
Navigate to http://localhost/k/admin/system/plugin/
Trying to upload /path/to/plugin.zip
/path/to/plugin.zip をアップロードしました!
```

**Review by chihiro-adachi — APPROVED** [review]

**Comment by chihiro-adachi** [comment]
@charleslee0212 
Thank you! it's merged.

**Comment by charleslee0212** [comment]
Of course!

**Pull request merged**
